services:
  authors:
    build: ./AuthorService
    ports:
      - 4000:4000
    command: npm run start-authors
  books:
    build: ./BookService
    ports:
      - 3000:3000
    command : npm run start-books
  categories:
    build: ./CategorieService
    ports:
      - 5000:5000
    command : npm run start-categories

